config/routes.rb
Rails.application.routes.draw do
  root 'index#index'
  get 'index/index'
  get 'index/list'

  # For details on the DSL available within this ile, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/verb.rb
class Verb < ApplicationRecord
  validates :infinitiv, presence: true
  validates :presens, presence: true
  validates :preteritum, presence: true
  validates :partizip_zwei, presence: true
  validates :translations, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :set_verbs

  def index
    @order = @verbs.map(&:id).shuffle
  end

  def list
  end

  private

  def set_verbs
    @verbs = Verb.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/index.html.erb
<%= render 'index/index/progress' %>
<%= render 'index/index/cards' %>

<script type="text/ecmascript">
  (function (w, $) {
    if (w.irven.CardsProcessor) {
      // verbs are shuffled from the server
      // TODO: no need to pass whole list for each request
      // if no verbst in local storage then ajax for verbs
      let cp = new w.irven.CardsProcessor(<%= @order.to_json %>);
      cp.init();
      cp.showNext()
    }
  })(window, jQuery);
</script>

app/views/index/index/_cards.html.erb
<div class="cards">
  <% @verbs.each do |v| %>
    <%=render 'index/index/cards/card', verb: v%>
  <% end %>
</div>

app/views/index/index/_progress.html.erb
<div class="progress-container">
  <div class="info-block">
    We do not track any of your personal data. All information is stored
    in your browser's local storage
  </div>
  <div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
</div>

app/views/index/index/cards/_card.html.erb
<div class="verb-card verb-<%= verb.id %>">

  <div class="card-body">
    <div class="card-title"><%= verb.infinitiv %></div>

    <div class="flip-card translation">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <span>Show translation</span>
        </div>
        <div class="flip-card-back">
          <%= verb.translations %>
        </div>
      </div>
    </div>

    <div class="answer-container">
      <%# targets = [:presens, :preteritum, :partizip_zwei] %>
      <% targets = [:preteritum, :partizip_zwei] %>
      <%= form_with url: root_path, authenticity_token: false do |f| %>
        <% targets.each do |symbol| %>
          <div class="form-group row">
            <div class="col-sm-12 input-container">
              <%= f.text_field symbol, placeholder: symbol, class: 'form-control verb-input', data: {answer: verb[symbol], tip: "#tip-#{verb.id}-#{symbol.id2name}"} %>
              <div id="tip-<%= verb.id %>-<%= symbol.id2name %>" class="input-tip alert alert-danger">
                <%= verb[symbol] %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="btn-container">
      <a href="#" class="btn btn-primary card-check">Check</a>
    </div>
  </div>

</div>

app/views/index/list.html.erb
<% unless @verbs.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>Infinitiv</th>
        <th>Translation</th>
        <th>Presens</th>
        <th>Preteritum</th>
        <th>Partizip zwei</th>
      </tr>
    </thead>
    <tbody>
      <% @verbs.each do |v| %>
        <tr>
          <td><%= v.infinitiv %></td>
          <td><%= v.translations %></td>
          <td><%= v.presens %></td>
          <td><%= v.preteritum %></td>
          <td><%= v.partizip_zwei %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info">
    No verbs in current database
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Irven: train irregular verb!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= "#{controller.controller_name} #{@body_class}".strip %>">

    <div class="main-wrapper">
      <%= render 'layouts/base/header'%>
      <div class="main-container container clear-top">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/base/footer'%>
  </body>
</html>

app/views/layouts/base/_footer.html.erb
<footer class="page-footer font-small blue">

  <div class="footer-copyright text-center py-3">© <%= Time.current.year %> Copyright:
    <a href="#">Irven</a>
  </div>

</footer>

app/views/layouts/base/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Irven", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Verb list", index_list_path, class: "nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>